# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Rose-J
tagline:          'A Jekyll theme'
description:      'explain the objective of the blog'
url:              https://rose-j.github.io/
baseurl:          /

author:
  name:           'Rose-J'
  url:            

paginate:         5



github:
  repo:           https://github.com/Rose-J/Rose-J.github.io
  bayesian:       https://github.com/Rose-J/Bayesian-Learning
